spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
  jpa:
    open-in-view: false # ???? ??? ???? lazy ?? ??
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true # SQL ??? ??? ?? ??
        show_sql: false # System ?? ?? ??
    database: h2
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
logging:
  level:
    org:
      hibernate:
        SQL: debug # Hibernate SQL ?? ??
        orm.jdbc.bind: trace # ???? ??? ?? ??? ??
jwt:
  secret: qwerasdfaseqwrewrqsdfadadsfasdfsdfasdvverbetbrbsadcsdacscasd
  expiration: 3600
